[workspace]
resolver = "2"
members = [
    "app",
    "cli",
    "lib",
    "tracker-fs",
]

[profile.release]
lto = true

[workspace.dependencies]
anyhow = "1.0"
indexmap = { version = "2.1", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
