[package]
name = "todo-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = { version = "4.3", features = ["derive"] }
todo-app = { path = "../app" }
todo-tracker-fs = { path = "../tracker-fs" }
