[package]
name = "todo-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
clap = { version = "4.3", features = ["derive"] }
indexmap = { workspace = true }
todo-app = { path = "../app" }
todo-lib = { path = "../lib" }
todo-tracker-fs = { path = "../tracker-fs" }
