[package]
name = "todo-app"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
config = "0.13"
serde = { version = "1.0", features = ["derive"] }
todo-tracker-fs = { path = "../tracker-fs" }
