[package]
name = "todo-app"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
config = { version = "0.13", features = ["preserve_order"] }
indexmap = { workspace = true }
serde = { workspace = true }
todo-tracker-fs = { path = "../tracker-fs" }
