[package]
name = "todo-tracker-fs"
version = "0.1.0"
edition = "2021"

[dependencies]
fs-err = "2.11"
indexmap = { workspace = true }
serde = { workspace = true }
thiserror = "1.0"
todo-lib = { path = "../lib" }
toml = { version = "0.8", features = ["preserve_order"] }
walkdir = "2.4"
