[package]
name = "todo-tracker-fs"
version = "0.1.0"
edition = "2021"

[dependencies]
fs-err = "2.11"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
todo-lib = { path = "../lib" }
toml = "0.8"
walkdir = "2.4"
